name: Run Python Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Executes every day at midnight UTC
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        pip install pandas camelot-py opencv-python ghostscript

    - name: Install System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript python3-tk

    - name: Run script and save result
      run: |
        python gerar_tabelas.py

    - name: Commit and Push Changes
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add *
        git commit -m "GitHub Actions $(date +'%Y-%m-%d')"
        git push

